name: Push to Cloudflare Pages

on:
  release:
    types: [published, prereleased]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.event.release.author.login }}"
          git config --global user.email "${{ github.event.release.author.email }}"

      - name: Push to cd-production
        if: github.event.release.prerelease == false
        run: |
          git push origin HEAD:cd-production

      - name: Push to cd-preview
        if: github.event.release.prerelease == true
        run: |
          git push origin HEAD:cd-preview
