name: Push to Cloudflare Pages

on:
  release:
    types: [published, prereleased]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare deploy hook
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
